apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: stephenobia/udagram-api-feed:v7
        resources:
          requests:
            memory: "4096Mi"
            cpu: "500m"
          limits: 
            memory: "4096Mi"
            cpu: "1"
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws/"
            readOnly: true
      volumes: 
        - name: aws-secret
          secret:
            secretName: aws-secret
        