apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: stephenobia/udagram-api-feed:v2
        resources:
          requests:
            memory: "512Mi"
            cpu: "261m"
          limits: 
            memory: "1024Mi"
            cpu: "512m"
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        